[theme]
base = "dark"
primaryColor = "#2dd4bf"
backgroundColor = "#101114"
secondaryBackgroundColor = "#1f2937"
textColor = "#f3f4f6"
font = "sans serif"

[server]
headless = true
address = "0.0.0.0"
port = 8501
enableCORS = false
enableXsrfProtection = false
runOnSave = true
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[client]
showErrorDetails = false
toolbarMode = "minimal"
